version: "3.3"
services:
  wordpressdb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    volumes:
      - wordpressdb_data:/var/lib/mysql
  wordpress:
    depends_on:
      - wordpressdb
    image: wordpress
    ports:
      - 80
    environment:
      WORDPRESS_DB_HOST: wordpressdb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
volumes:
  wordpressdb_data: {}  